### ISSUE TITLE
Add RTL Support

### ISSUE THREAD

**Issue by minusium** [cedvdb/phone_form_field#103]
## Code:
```
          PhoneFormField(
            autofocus: true,
            defaultCountry: IsoCode.IR,
            validator: PhoneValidator.compose([
              PhoneValidator.required(
                  errorText: context.strings.emptyFieldError),
              PhoneValidator.validMobile(
                  errorText: context.strings.invalidMobileError),
            ]),
            decoration: InputDecoration(
              labelText: context.strings.phoneNumberLabel,
              prefixIcon: const Icon(Icons.phone),
            ),
            textInputAction: TextInputAction.next,
            textDirection: TextDirection.ltr,
          ),
```

## Actual Behavior
![image](https://user-images.githubusercontent.com/21140798/163971731-837ba2e1-4875-4a3e-a969-7a48e698dd20.png)

## Expected Behavior:
![image](https://user-images.githubusercontent.com/21140798/163974263-73780f04-2184-4ea7-85e7-55b0bfca7172.png)

**Comment by cedvdb** [comment]
This would be a nice addition indeed.

**Comment by minusium** [comment]
I'm working on it right now, this is where I got so far.

![image](https://user-images.githubusercontent.com/21140798/163979856-d1be4fbf-aa2a-443f-8b30-b075ed4ce436.png)
