### ISSUE TITLE
Change from v4.6.0 to v5.0.0 causes flag icon alignment swap

### ISSUE THREAD

**Issue by JDVila** [cedvdb/phone_form_field#108]
First of all, thank you for this amazing Flutter/Dart package!

There is an odd issue where for some reason, the flag icon and country code number is placed on the right side of the field, but the invisible dropdown button is still on the left side.

**v4.6.0 and below:**
![Screenshot_1651179508](https://user-images.githubusercontent.com/20868172/165846833-18f9709a-f4fd-4f80-a8e5-a359a4c27ae0.png)

**v5.0.0 and greater:**
![Screenshot_1651179568](https://user-images.githubusercontent.com/20868172/165846883-12c35965-8bd4-424c-903a-b64df8d1e8a3.png)

**Note:** the dropdown button looks grey only because I tabbed onto it - normally it is transparent.

**Comment by cedvdb** [comment]
It is probably due to the PR that added Right to left support. @minusium

**Comment by cedvdb** [comment]
Did you test on 5.0.0 exactly or `^5.0.0` ?

Right to left support was added in `5.0.2` @minusium

**Comment by minusium** [comment]
Yes seems like it's my fault, but I'm kind of busy. I'll look into it as soon as I can.

**Comment by JDVila** [comment]
Thank you @cedvdb and @xmine64 - looks like if I explicitly set the text direction: i.e.: `textDirection: TextDirection.ltr` or `textDirection: TextDirection.rtl` in my widget, the glitch goes away. If you all would like, I could make a PR where I initialize `TextDirection? textDirection = TextDirection.rtl,` on line 123 of the file `phone_form_field.dart` for a patch release - what are your thoughts?

**Comment by cedvdb** [comment]
I'm still having trouble understanding the problem here. Since you did not pass any value, the default should be used. Do you have a locale setup in your material app ? If so could you share your `MaterialApp` code ?

**Comment by JDVila** [comment]
Hello! Unfortunately, adding a Locale in the `MaterialApp` widget changed nothing:

```
@override
  Widget build(BuildContext context) {
    return MaterialApp(
        locale: Locale('en', 'US'),
    ....
```

However, adding `TextDirection` to the `PhoneFormField` widget did fix the glitch:

```
child: PhoneFormField(
                                textDirection: TextDirection.ltr,
....
```
Hope that helps!

**Comment by xmine64** [comment]
> I'm still having trouble understanding the problem here. Since you did not pass any value, the default should be used. Do you have a translation setup in your material app ? If so could you share your MaterialApp code ?

I check if `textDirection` of phone form field is not equal with `Directionality.of(context)` then I invert place of country chip. I forgot to consider what should happen when textDirection is null.

**Comment by cedvdb** [comment]
Would it be possible to update that soonish ? Someone requested to push a new version with the updated metadata as they seemed to be outdated.

**Comment by cedvdb** [comment]
Fixed.
