### ISSUE TITLE
Passing inputFormatters to PhoneFormField has no effect

### ISSUE THREAD

**Issue by spakanati** [cedvdb/phone_form_field#114]
It's possible to pass inputFormatters to PhoneFormField, but the inputFormatters are never passed down to any internal widgets, so it seems the default inputFormatters on PhoneFieldState are always used. It would be useful to be able to override the default inputFormatters that remove all non-numeric input.

**Comment by cedvdb** [comment]
Note that it already allows only digits (roman and arabics) and punctuation currently. 

If you need to be less permissive, I'll gladly review a PR that allows the defaults to be overriden.

**Comment by cedvdb** [comment]
Is this something you are looking to implement ?

**Comment by cedvdb** [comment]
fixed in upcoming version
