### ISSUE TITLE
Always invalid when the text is set using the controller (PhoneController.value)

### ISSUE THREAD

**Issue by NeatFastro** [cedvdb/phone_form_field#116]
I can set the input through the controller e.g.
`phoneNumberController.value = PhoneNumber.fromRaw(123);`
But after this when I call the parent Form's validate() method then PhoneFormField() validator becomes active,
if I edit the number a little e.g. erase the last digit and then type it again then the validate() method of the parent Form widget works as intended

**Comment by cedvdb** [comment]
I'm not sure I understand what you are saying. Can you provide a sample code ?

**Comment by cedvdb** [comment]
Can you submit a fix ?

**Comment by philitell** [comment]
Is there a solution for this issues?

**Comment by cedvdb** [comment]
> Is there a solution for this issues?

What is the issue exactly ? Do you have a repro ?

**Comment by philitell** [comment]
Setting a valid phonenumber by the controller (without editing the phone-number-field via the ui) is not recognized by the validator. It makes no difference which AutoValidationMode is used - bug is always present.
Only if you edit the field (delete a digit and re-enter the digit) and submit the form then the validator works. 

Steps to reproduce:
 1. set valid phone number via controller
 2. submit form without clicking oder editing the form field

Expected result: 
 - Form is valid

Actual result:
 - Form is invalid

```dart
import "package:flutter/material.dart";
import "package:phone_form_field/phone_form_field.dart";

class TestApp extends StatefulWidget {
  const TestApp({Key? key}) : super(key: key);

  @override
  State<TestApp> createState() => _TestAppState();
}

class _TestAppState extends State<TestApp> {
  final _formKey = GlobalKey<FormState>();
  final PhoneController _phoneController = PhoneController(null);

  @override
  void initState() {
    _phoneController.value = PhoneNumber.parse("+436641234123");
    super.initState();
  }

  @override
  void dispose() {
    _phoneController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Form(
        key: _formKey,
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.all(16.0),
              child: PhoneFormField(
                autovalidateMode: AutovalidateMode.disabled,
                controller: _phoneController,
                shouldFormat: false,
                defaultCountry: IsoCode.AT,
                decoration: const InputDecoration(
                  labelText: "Phone",
                ),
                validator: PhoneValidator.compose([
                  PhoneValidator.required(errorText: "Please enter phone number"),
                  PhoneValidator.valid(),
                ]),
              ),
            ),
            ElevatedButton(
              onPressed: () {
                bool isValid = _formKey.currentState!.validate();
                if (isValid) {
                  _formKey.currentState!.save();
                  print("Form saved");
                } else {
                  print("Form invalid");
                }
              },
              child: const Text("submit"),
            )
          ],
        ),
      ),
    );
  }
}

```

**Comment by cedvdb** [comment]
Thanks, this was an easy fix, will upload next release shortly

**Comment by williamrech** [comment]
@cedvdb I`m having the exact same issue.
In my case, some phones are saved with the isocode along the nsn. The plugin correcs this but only if editing the ui as @philitell described.
Do you have any date for the next release?

Thank you.

**Comment by cedvdb** [comment]
@williamrech I do not have open time slots for this package in the upcoming month. Feel free to have a look.  It might be useful if you could give reproduction steps in case someone wants to have a look.

**Comment by williamrech** [comment]
As an example, the phone passed to the controller in this case is "+5551999163181". When typing an extra "0", the country code "55" is removed, then the fone gets correctly formatted when removing the "0".

![May-23-2023 13-55-19](https://github.com/cedvdb/phone_form_field/assets/66319068/509dee45-1bc0-468b-8cd4-307be342b1bc)

I was not able to make the field behave correctly without user interaction, thus the form could not be successfuly validated.

**Comment by cedvdb** [comment]
Could you reopen another issue about this ? This is a different issue and is actually in this package

https://github.com/cedvdb/phone_numbers_parser/issues
