### ISSUE TITLE
Flag / Phone Number Hidden when not focus on version > 6.10

### ISSUE THREAD

**Issue by riorizki** [cedvdb/phone_form_field#122]
Hi, why is the phone number/flag always hidden when not focused on version 6.11 - 7.0
in version 6.10, the flag can show even not focused to text field

<img width="498" alt="Screen Shot 2022-07-26 at 23 34 46" src="https://user-images.githubusercontent.com/28858623/181061860-c287891a-af0d-4a7a-88fd-5ea19bb4029c.png">
<img width="482" alt="Screen Shot 2022-07-26 at 23 34 41" src="https://user-images.githubusercontent.com/28858623/181061964-0171f10d-ce7e-478b-8994-d9f3cdce1b28.png">

Thank you

**Comment by cedvdb** [comment]
That's on version 7.0.0 ? That looks like a bug

**Comment by cedvdb** [comment]
fixed in next release
