### ISSUE TITLE
There is no way to disable the list with countries

### ISSUE THREAD

**Issue by Polyariz** [cedvdb/phone_form_field#123]
Hello! When clicking on a country code, a list of countries appears. I need a list of countries to not appear when clicking on a country code, how can I disable this?

**Comment by cedvdb** [comment]
What's the use case ? Only one country available ?

**Comment by cedvdb** [comment]
You could make a no-op CountryNavigator and add it to the list here:

https://github.com/cedvdb/phone_form_field/blob/dev/lib/src/widgets/country_selector/country_selector_navigator.dart

**Comment by cedvdb** [comment]
fixed in upcoming version

**Comment by Polyariz** [comment]
In my case, it is necessary to manage the ability to change the country. For example, the app is only for one country.

**Comment by Polyariz** [comment]
I can also help you with the translation of the plugin into Ukrainian

**Comment by cedvdb** [comment]
It is done in the new version. You are welcome to help
