### ISSUE TITLE
reset throw an error

### ISSUE THREAD

**Issue by Nekketsu-GIT** [cedvdb/phone_form_field#138]
Hello I am using your package in a particular context. Because we use bloc pattern, we develop this packages that facilitate bloc integration with form [](https://pub.dev/packages/flutter_floc) .
I want to integrate your package to build phone number field and it works fine except the reset functionnality. 
It throws an TypeErrorImpl, it is like null value is no longer accepted in the controller.
But it seems to work fine in your example. So it is more an call for help than an issue. 
![Capture d’écran du 2022-08-12 12-36-26](https://user-images.githubusercontent.com/54125039/184337655-036e2d77-77c2-47c0-9668-993f22b6c170.png)
![Capture d’écran du 2022-08-12 12-35-09](https://user-images.githubusercontent.com/54125039/184337656-6d7cc4bb-a419-4e29-90a9-f89302e4ce1f.png)
![Capture d’écran du 2022-08-12 12-34-43](https://user-images.githubusercontent.com/54125039/184337658-d42deaad-5718-4b67-ba5c-f0fc92a0bdb3.png)
In the picture you can see the error throwed, and some other picture that works fine

Here is the implementation 

`
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_floc/flutter_floc.dart';
import 'package:phone_form_field/phone_form_field.dart';

class PhoneFormFieldBlocBuilder<T extends FormBloc> extends StatefulWidget {
  /// Fieldname to map with a field of the parent FormBloc in the widget tree
  final String fieldName;
  final String? hint;
  final IsoCode? initialCountryCode;
  final InputDecoration decoration;

  PhoneFormFieldBlocBuilder({
    Key? key,
    required this.fieldName,
    this.decoration = const InputDecoration(),
    this.hint,
    this.initialCountryCode,
  }) : super(key: key);

  @override
  _PhoneFormFieldBlocBuilderState createState() =>
      _PhoneFormFieldBlocBuilderState<T>();
}

class _PhoneFormFieldBlocBuilderState<T extends FormBloc>
    extends State<PhoneFormFieldBlocBuilder> {
  late PhoneController _controller;

  @override
  void initState() {
    super.initState();
    _controller = PhoneController(null);
    _controller.addListener(() => setState(() {}));
  }

  void dispose() {
    super.dispose();
    _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<T, FormBlocState>(
      buildWhen: (previous, current) =>
          previous.fields[widget.fieldName] != current.fields[widget.fieldName],
      builder: (context, state) {
        return PhoneFormField(
          controller: _controller,
          decoration: _buildDecoration(context),
          validator: PhoneValidator.none,
          countrySelectorNavigator: CountrySelectorNavigator.modalBottomSheet(),
          defaultCountry: widget.initialCountryCode != null
              ? widget.initialCountryCode!
              : IsoCode.FR,
          onChanged: (phone) {
            print(phone!.international);
            context.read<T>().updateField(widget.fieldName,
                OurPhoneNumber(isoCode: phone!.isoCode, nsn: phone.nsn));
          },
        );
      },
      listener: (context, state) {
        if (context.read<T>().state.status == FormStatus.pure) {
          print("pure");

          if (_controller.value == null) {
            print("null");
          } else {
            // _controller.value = PhoneNumber(
            //     isoCode: widget.initialCountryCode != null
            //         ? widget.initialCountryCode!
            //         : IsoCode.FR,
            //     nsn: '');

            _controller.reset();
          }
        }
      },
    );
  }

  InputDecoration _buildDecoration(BuildContext context) {
    return widget.decoration.copyWith(
      errorText: context.read<T>().fieldError(widget.fieldName),
    );
  }
}

`

Hope we can found a solution =

**Comment by cedvdb** [comment]
I'm letting this open in case some other members want to chime in to help you. Personally I do not furnish help

**Comment by Nekketsu-GIT** [comment]
i will make a pull request if i found there is a problem
thank you

**Comment by cedvdb** [comment]
Do you remember if the issue was with the package ?

**Comment by cedvdb** [comment]
There does not seem to be an issue resetting here via the example. Closing for now
