### ISSUE TITLE
[bug] PhoneNumber option phoneNumberType is not working 

### ISSUE THREAD

**Issue by emri99** [cedvdb/phone_form_field#14]
### Problem encountered

The option `phoneNumberType` of `PhoneNumberField` widget seems useless.

### Reproduce step

* Run example project
* Ensure option _mobile phone number only_ is checked
* Type a valid fixed line phone

Expected behavior: 
* field should be flagged as invalid

Current behavior:
* no error visible

**Comment by cedvdb** [comment]
That's a regression, I'll add an unit test for that

**Comment by cedvdb** [comment]
fixed and unit tested in https://github.com/cedvdb/phone_form_field/pull/17

**Comment by emri99** [comment]
Test unit are failing on my side on :
* `Should tell when a phone number is not valid` line 170, pos 
* `Should tell when a phone number is not valid for a given phone number type` line 192

Does these tests passed for you ?
