### ISSUE TITLE
Country iso2 resets itself when phone number is empty

### ISSUE THREAD

**Issue by naamapps** [cedvdb/phone_form_field#140]
Hey,
There is a bug that occurs when the phone number itself is empty.

The iso 2 always resets itself to the default country.
So choosing the country doesn't affect the form field - it stays with the same default country.

Only after typing some digits, and trying to change the country, then it works.
But after removing all digits, it resets to default country.

I think the best behaviour is to keep the chosen country no matter what happens.
Only at the initialization of the form field, the default country should be used (after checking there is no initial form value).

Thanks

**Comment by naamapps** [comment]
@cedvdb please help

**Comment by cedvdb** [comment]
I'm busy, this project is open source, that means everyone can shime in and help and fix things.

**Comment by cedvdb** [comment]
@naamapps can you provide a repro ?

**Comment by cedvdb** [comment]
When the field resets itself, the original default country will appear. If the user remove the phone number the country code he has picked stays there. Unless I'm misunderstanding something there does not seem to be anything wrong here.

Feel free to comment back and I will reopen, I've just not been able to find an issue in the version that is being worked on now.
