### ISSUE TITLE
Can't change flag size in draggable buttom sheet while keep showing the country code

### ISSUE THREAD

**Issue by mohn93** [cedvdb/phone_form_field#149]
Does this line serve any purpose?
`            size: showDialCode ? null : flagSize,
`
Should I create a pull request and remove the condition to always pass the flag size?

**Comment by cedvdb** [comment]
Where have you find this line ? github search does not yield anything

**Comment by cedvdb** [comment]
Indeed that line is weird, I don't think there is any need for a ternary there

**Comment by mohn93** [comment]
@cedvdb , Opened this merge request #150
