### ISSUE TITLE
FlagSize does not work on ListTile leading 

### ISSUE THREAD

**Issue by danielesilvestre** [cedvdb/phone_form_field#151]
Hi there,
I hope you are doing well.

There is a bug with the flagSize of the country selector for draggableBottomSheet.
when I try to set flagSize for the icon on doesn't work properly. It is getting the flag in a wrong shape.

To reproduce it, just try to set a size for the flag into on country selector navigator and you will be able to see that the size does not change. 

![image](https://user-images.githubusercontent.com/9205086/206700188-bb3517e1-6352-4160-90d0-d5f9b78aaa31.png)

**Comment by cedvdb** [comment]
Could be an issue with the circle flags library https://github.com/cedvdb/flutter_circle_flags/blob/main/lib/circle_flags.dart

Do you have the issue with this package ? https://github.com/cedvdb/flutter_circle_flags/blob/main/lib/circle_flags.dart

I'll review a PR

**Comment by cedvdb** [comment]
Should be fixed in next release
