### ISSUE TITLE
[Bug] Field resets when phone number starts from country code

### ISSUE THREAD

**Issue by nahimilega** [cedvdb/phone_form_field#155]
While entering the phone number... the phone number field resets itself when the country code matches the first two digits of the mobile number.

Steps to Reproduce
1.  Open the demo (https://cedvdb.github.io/phone_form_field/#/) and select a country from the country selector. For example... let's say India (code +91)
2. Start typing the phone number. Type 91

The field will reset itself
So effectively user can't enter the phone number which is +91 9185XXXXXX
This could be reproduced with other countries as well.

**Comment by cedvdb** [comment]
needs a fix in the parsing library https://github.com/cedvdb/phone_numbers_parser/issues/35

**Comment by cedvdb** [comment]
Thanks for this one, I'll change the behavior to something more acceptable: remove the country code only if an exit code is present
