### ISSUE TITLE
intl

### ISSUE THREAD

**Issue by VladilenC** [cedvdb/phone_form_field#167]
Because every version of flutter_localizations from sdk depends on intl 0.18.0 and phone_form_field 7.0.6 depends on intl ^0.17.0, flutter_localizations from sdk is incompatible with phone_form_field 7.0.6.
And because no versions of phone_form_field match >7.0.6 <8.0.0, flutter_localizations from sdk is incompatible with phone_form_field ^7.0.6.
So, because Maghelp depends on both phone_form_field ^7.0.6 and flutter_localizations from sdk, version solving failed.

**Comment by cedvdb** [comment]
what version of flutter are you using

**Comment by VladilenC** [comment]
3.9.0-9.0.pre.16

С уважением, Чупин В.В.

От: cedvdb
Отправлено: 18 марта 2023 г. в 15:01
Кому: cedvdb/phone_form_field
Копия: Vladilen; Author
Тема: Re: [cedvdb/phone_form_field] intl (Issue #167)

what version of flutter are you using
