### ISSUE TITLE
Field loses focus if `isCountryChipPersistent` is set to false with Flutter > 3.10

### ISSUE THREAD

**Issue by Cteq3132** [cedvdb/phone_form_field#175]
Hello! 

Thanks for your work on this package. I updated to Flutter 3.10.1 today and found a problem with the field focus when the country chip appears.

To reproduce the issue, just run the example, unfocus the field by tapping on the dropdown, and focus the field again --> The field loses focus right after the country chip had appear.

https://github.com/cedvdb/phone_form_field/assets/87450402/cb1b2e49-fb2b-45b2-b275-74d0dd2cb746

Expected behaviour: The field stays focus

**Comment by cedvdb** [comment]
It's a bit hard to see that the field loses focus in the video you posted because the keyboard is hiding the field. Is that the issue ? 

I mean did it scroll prior to this o the field stayed in the view ?

**Comment by cedvdb** [comment]
I believe this is no longer an issue. Can you confirm ?

**Comment by cedvdb** [comment]
should be fixed in 9.0.1
