### ISSUE TITLE
Consider making the dependency on circle_flags optional

### ISSUE THREAD

**Issue by xvrh** [cedvdb/phone_form_field#181]
I'm a bit concern about the latest direction of `circle_flags` which use network images. It's not working for use case. Also the dependency on `flutter_cache_manager` is too invasive: in term of number of transitive dependencies and hard to use unit tests with it.

Can we find a way where the `circle_flags` dependency is optional and we can replace it with a library which bundle the assets in the package?

**Comment by cedvdb** [comment]
I had another version of circle flags which used only vanilla packages, maybe that would solve the issue at hand all in itself ?

How could circle flag change to be more in line with what people desire ?

I feel like Network image for reduced is more of a pro than a con, as images can be preloaded. The flutter cache manager isn't necessarily a requirement..

**Comment by xvrh** [comment]
Thanks for the feedback.

Here is what I would do:
- Drop the direct dependency on `circle_flags`
- Add a parameter `Widget Function(String isoCode) flagBuilder` to `PhoneFormField` and replace all internal uses of `CircleFlag` with this builder
- Explain in the README of `phone_form_field` how one can provide the builder:
```dart
import 'package:circle_flags/circle_flags.dart`

PhoneFormField(
  //..
  flagBuilder: (isCode) => CircleFlag(isoCode),
);
```

- Create 2 variants of the `circle_flags` package: `circle_flags_assets` & `circle_flags_network`.
- Also it opens the door to more flexibility for the user: use some square flags, bundle the flags as an Icon Font, use PNGs, optimised SVG... Lot of possibilities in the hand of the user of the package.

**Comment by cedvdb** [comment]
There is two issues here: 
  1. how can circle_flags improve
  2. adding a builder for the flag
  
To me it sounds like 1 is the first step that should be taken as it would yield the most return on investment, for most people. 

Loading flags via network solves three issues: 
  - Flags are added to flutter_circle_flags that are not necessarily used by phone form field library
  - This solves the issues of being out of date with the original HatScript package that is updated more frequently
  - This makes the package easier to maintain as it is up to date with the original repo.

It brings the following issues:
  - we are at the mercy of the package author. A github action that clones the original repository as a safe guard and uses links from flutter_circle_flags instead could be added, but I don't see the point, the problem has just switched hands.
  - a dependency was added for caching.

It seems solvable by:
  - adding a FlagLoader input parameter to phone_form_field, so people can load images from any link, or their own assets
  - removing that cache dependency by using dart http and a quick file cache made of vanilla code.

**Comment by xvrh** [comment]
For me **go back to assets with circle flag** is enough.
It's only 150KB of compressed data and we have clear control over what we put in our app.

The issues you list above for network images, for me those are **major** issues. We cannot rely on third party website for security and reliability reasons. Even if you remove `flutter_cache_manager` (which for me is a show-stopper), it is still too brittle.

Thanks for considering.

**Comment by cedvdb** [comment]
Okay, can you submit a PR for reverting those changes into circle flags ? I'll deal with the changes here.

**Comment by xvrh** [comment]
We can theoretically have tree-shakable flags with an icon font but that would requires the user to explicitly list all the flags he wants in the code.
ie:

```dart
PhoneFormField(
  flags: {'fr': CircleFlags.fr, 'us': CircleFlags.us}
);
```

I also hope that at some point we can have normal assets to be tree-shakable: https://github.com/flutter/flutter/issues/64106.

**Comment by cedvdb** [comment]
Should now be fixed in latest version.

You also have the possibility to implement a custom asset loader too. My time is done here though. Feel free to ask for maintainer status if you wish.
