### ISSUE TITLE
Long pressing phone field to paste phone number does not work on Android 

### ISSUE THREAD

**Issue by omartins365** [cedvdb/phone_form_field#182]
How to enable the copy and paste context menu after long press on android?

**Comment by avive** [comment]
We are having the same issue. Paste is not available in both iPhone and Android. How to enable users to paste in a number? This is key for this type of control. Thanks for this great widget!

**Comment by hellyab** [comment]
Same issue on iOS too

**Comment by avive** [comment]
This widget is pretty much useless for real-world usage without a functional paste capability.

**Comment by cedvdb** [comment]
Is anyone willing to work on that ?

**Comment by simplenotezy** [comment]
Fixed here, along with a temporary workaround until it's been merged: https://github.com/cedvdb/phone_form_field/pull/198

**Comment by cedvdb** [comment]
Anyone willing to add a test for that PR ?
