### ISSUE TITLE
Make flag optional in country selector

### ISSUE THREAD

**Issue by JelleBuning** [cedvdb/phone_form_field#184]
The described flags:
![image](https://github.com/cedvdb/phone_form_field/assets/37436672/d01e0167-7ec7-466b-9387-47da4201f7ac)

**Comment by yunweneric** [comment]
Hi  👋
I will like to work on this issue

**Comment by zhangdc** [comment]
Because it involves national political issues

**Comment by cedvdb** [comment]
This can be resubmitted to https://github.com/cedvdb/flutter_country_selector
