### ISSUE TITLE
[Bug] Field resets when phone number starts with the pattern (011-country code)

### ISSUE THREAD

**Issue by BijayJaishi** [cedvdb/phone_form_field#185]
There is issue while giving input to phone field. Field resets when phone number starts with the following pattern:

011XXX
where XXX is country code 
for e.g  011374 for armenia, 011229 for Benin

Used package is the latest one i.e  phone_form_field: ^8.1.0

**onChange value are printed in given figure:**

![Screenshot 2023-07-10 at 09 22 00](https://github.com/cedvdb/phone_form_field/assets/35502191/5c1d64d5-59cc-46f5-bf82-0d029e4f0601)

**sample video is given here**

https://github.com/cedvdb/phone_form_field/assets/35502191/f056529b-93d9-4b72-a370-e4561fef26a0

@cedvdb could you check this issue please.

**Comment by cedvdb** [comment]
I'm not currently available to work on this now or in the near future. 

I'll review a PR if one appears

**Comment by sahilmehra98** [comment]
Facing same issue with country code of India

**Comment by cedvdb** [comment]
I tried it in the demo and it seems like it is no longer an issue.

Try it here https://cedvdb.github.io/phone_form_field/

![image](https://github.com/cedvdb/phone_form_field/assets/22280985/2075899c-0533-46c6-987a-cacd2db12858)
