### ISSUE TITLE
[Question] how to fill field when editing phone number ?

### ISSUE THREAD

**Issue by saifonglee** [cedvdb/phone_form_field#188]
I have got the phone number in this format $countryCode.' '.$nsn: +226 70 20 30 40
I want to set an initial value for the field with this number for editing. but the field needs a PhoneNumber() as initialValue. 
what I've done, I put in phoneNumber() the isoCode, and the nsn but it not working. 
the field is still empty.

how can I format the international phone number to be able to set as initialValue in phone the form field?

**Comment by sumitsharansatsangi** [comment]
Try  ```PhoneNumber.parse("+226 70 20 30 40")```

**Comment by cedvdb** [comment]
@saifonglee 

Indeed, try what was suggested above if you haven't already. I'm going to close this issue for now, feel free to comment back if you are hitting more issues.

**Comment by saifonglee** [comment]
Thank you @sumitsharansatsangi. 
It's now working fine.
