### ISSUE TITLE
Unmoddificable padding

### ISSUE THREAD

**Issue by felixmarrero** [cedvdb/phone_form_field#200]
Padding that cannot be modified to the left of the flag and to the right of the country code

**Comment by cedvdb** [comment]
This issue is ambiguous. Which flag ?

**Comment by felixmarrero** [comment]
![flag](https://github.com/cedvdb/phone_form_field/assets/129766523/dab1d948-cfd0-4a72-b376-b2b53298b8d6)

**Comment by cedvdb** [comment]
If you decide to implement this take care that the flag and the text must be aligned under the different scenarios:

  - underline / outline input border
  - with / without label
  - ...

**Comment by zhangdc** [comment]
> 这个问题是有歧义的。哪面旗帜？

Because the national emblem involves some national sovereignty issues, not displaying the national emblem directly can avoid many political issues

**Comment by cedvdb** [comment]
Fixed in 9.0.1
