### ISSUE TITLE
Unmodificable flagSize in country selector dialog

### ISSUE THREAD

**Issue by felixmarrero** [cedvdb/phone_form_field#201]
Internally I see that the flag size property exists at 40 to change the size of the flags in the country selector but when calling CountrySelectorNavigator.dialog() there is no such option.

**Comment by cedvdb** [comment]
Is this still an issue ?

**Comment by cedvdb** [comment]
should be reopened in this repo if this is still an issue https://github.com/cedvdb/flutter_country_selector
