### ISSUE TITLE
FlagCache is not exported

### ISSUE THREAD

**Issue by aggeloskoutanis** [cedvdb/phone_form_field#207]
When trying to override `Future<Country?> navigate(BuildContext context, FlagCache flagCache);`, FlagCache is not exported and thus I cant override this method. 

Please exported it so it will become available.

**Comment by cedvdb** [comment]
The flag cache seems unnecessary in retrospect, but some metrics, even if eye balled should be checked before doing anything. It it is indeed unnecessary it can probably be removed from https://github.com/cedvdb/flutter_circle_flags

**Comment by cedvdb** [comment]
should not be an issue in v9.0.1
