### ISSUE TITLE
New numbering for Cuba's lines

### ISSUE THREAD

**Issue by AndryCU** [cedvdb/phone_form_field#210]
The new Cuban mobile lines will have a change in their numbering, will add the+5363****** and the package does not recognize this new numbering according to this published note https://www.etecsa.cu/es/nueva/numeracionmovil

**Comment by cedvdb** [comment]
You can update the metadata following the instructions in the readme

**Comment by adonisRodxander** [comment]
@cedvdb What exactly do you mean? Can't the package be upgraded to support this change?

**Comment by cedvdb** [comment]
@adonisRodxander sorry wrong package, this is the package: https://github.com/cedvdb/phone_numbers_parser  in the readme there is a section about how to upgrade the metadata to be in line with google

**Comment by adonisRodxander** [comment]
When I updated to the latest version of the package, the error disappeared, feel free to close this issue. Good job
