### ISSUE TITLE
document enhancement about override flags

### ISSUE THREAD

**Issue by yousefak007** [cedvdb/phone_form_field#222]
hi, thank you for doing this library

I see some people complain about some inaccurate flags, and this library depends on `circle_flags` lib, and it needs to change or update flags on that library first

for example, Saudi and Iraq flags are inaccurate 

for an easy solution and rather than waiting, I can override that package assets by doing this:

I just made `packages/circle_flags/assets/svg/` folder:

![image](https://github.com/cedvdb/flutter_circle_flags/assets/46021584/2f1c181b-d61a-4146-814a-f03a26fccbb8)

then in `pubspec.yaml` I added in assets:

```yaml
  assets:
    - packages/circle_flags/assets/svg/
```
![image](https://github.com/cedvdb/flutter_circle_flags/assets/46021584/c3c47d3a-2ca0-4c08-8c95-0075a0337352)

it will be helpful if this information is added to the documentation of this library

**Comment by cedvdb** [comment]
The original flags are there: https://github.com/HatScripts/circle-flags and should be changed there

**Comment by Lionapi** [comment]
Hello,

i tried to use the version 9.2.3 of Phone_form_Field and i got this error :
see the attached picture.
![error_flutter](https://github.com/cedvdb/phone_form_field/assets/22023011/e58a99ce-a7ea-4fb9-9a59-b7948198ee07)

can you help me please ?

**Comment by cedvdb** [comment]
@Lionapi What does that have to do with flags ? Change to `...PhoneFieldLocalization.delegates` (add ... in front)

**Comment by Lionapi** [comment]
@cedvdb I know there's no connection between the two, but after looking for a way to contact you, here's the one I found.
However, even adding it in front as you say, the same error persists and i'm still stuck.

**Comment by cedvdb** [comment]
Please create your own issue, with a code snippet instead of a screenshot.
