### ISSUE TITLE
Adding `hu` localisation & fixing `fr` 

### ISSUE THREAD

**Issue by emri99** [cedvdb/phone_form_field#225]
Hello !

I would like to create a pull request for Hungarian locale.
I've notice 1/2 mistakes in French translations.

Do you prefer 2 PR for each subject or one for both ?

(I will open PRs here and [`flutter_country_selector`](https://github.com/cedvdb/flutter_country_selector))

**Comment by cedvdb** [comment]
Hey, you can makee one for localizations

**Comment by emri99** [comment]
* Fixed here in https://github.com/cedvdb/phone_form_field/pull/226
* Fixed on [`flutter_country_selector`](https://github.com/cedvdb/flutter_country_selector)) in https://github.com/cedvdb/flutter_country_selector/pull/7
