### ISSUE TITLE
Custom theme for search box decoration not applied.

### ISSUE THREAD

**Issue by aelrahmanashraf** [cedvdb/phone_form_field#228]
I tried to make the search box look different in CountrySelectorNavigator, but it's not working. When I checked the code, it seems like the search box design settings are not reaching the PageNavigator, which might be why it's not working.

**Comment by cedvdb** [comment]
Need repro

**Comment by aelrahmanashraf** [comment]
After checking again, I can't add custom style to the searchBoxDecoration. The code is missing the part where the custom style is applied to the page. At the end, I forked the repo and applied the style myself here.

![image](https://github.com/cedvdb/phone_form_field/assets/124633867/58df001e-e477-4deb-b316-2613baced014)

**Comment by cedvdb** [comment]
Can't you do it by changing the `Theme` around phone form field ?

**Comment by aelrahmanashraf** [comment]
Doing this will just change the form field theme itself but not the search box inside the country selector page.

**Comment by aelrahmanashraf** [comment]
I have forked the repo and applied it anyway. You can take a look at the pull request.

**Comment by cedvdb** [comment]
It seems that this is an issue with flutter similar to this issue https://github.com/flutter/flutter/issues/145824 (but instead of language it's a theme issue)

**Comment by cedvdb** [comment]
I believe this is fixed in v10 or I may have misunderstood the issue
