### ISSUE TITLE
Cannot find PhoneFieldLocalization.of(context).countryName(isoCode)

### ISSUE THREAD

**Issue by MariosKoni** [cedvdb/phone_form_field#229]
In the changelog of version 9.0.0, there is a breaking change where you suggest to use `PhoneFieldLocalization.of(context).countryName(isoCode)` instead of `LocalizedCountryRegistry`, but such function is not present (`countryName`).

**Comment by cedvdb** [comment]
It seems like it has moved into the CountrySelector package: 

https://github.com/cedvdb/flutter_country_selector/blob/main/lib/src/localization/localization.dart

**Comment by aggeloskoutanis** [comment]
> It seems like it has moved into the CountrySelector package, which is used internally by this library:
> 
> https://github.com/cedvdb/flutter_country_selector/blob/main/lib/src/localization/localization.dart
> 
> imo this should either be documented or an alias should be added to `PhoneFieldLocalization` towards `CountrySelectorLocalization`

So at the moment, how do we access the localizations?

**Comment by cedvdb** [comment]
`CountrySelectorLocalization.countryName()`

**Comment by aggeloskoutanis** [comment]
@cedvdb Could you publish the version 9.2.0 to pub.dev that supports circle_flags: ^5.0.0, since flutter_country_selector also depence on circle_flags: ^5.0.0. Otherwise, I cant use flutter_country_selector with 9.1.0 version of phone_form_field.

thanks for your fast replies. I appreciate it.

**Comment by cedvdb** [comment]
It is already there `9.2.1` atm
