### ISSUE TITLE
[Documentation] Add API doc

### ISSUE THREAD

**Issue by emri99** [cedvdb/phone_form_field#23]
To give developer helpful hints in IDE as well as getting more static analysis points on pub.dev, API doc may be valuable.

**Comment by cedvdb** [comment]
Yes especially since I added the BasePhoneFormField class the /// commented doc is not on the exported class anymore (which I noticed yesterday).

**Comment by cedvdb** [comment]
Just to clarify, you meant this with your original comment https://dart.dev/tools/dartdoc or just the comments ?

**Comment by emri99** [comment]
I was thinking of `///` comments.
The idea behind my proposition was to get more helpful hints via IDE and to increase the package points on pub.dev.

To be honest, I don't really get the pros of pushing api doc inside repo for public packages as it's accessible on pub.dev package page.
