### ISSUE TITLE
How do you use the localization delegate. Type `Set<LocalizationDelegate<dynamic>>` cannot be assigned to `LocalizationDelegate<dynamic>`

### ISSUE THREAD

**Issue by Lionapi** [cedvdb/phone_form_field#238]
When i use the new version of phone_form_field i got an error, where should i place it correctly ?
![error_flutter](https://github.com/cedvdb/phone_form_field/assets/22023011/12b06b78-69c2-46a5-b90f-44b680f4154f)

localizationsDelegates: const [
  GlobalMaterialLocalizations.delegate,
  GlobalWidgetsLocalizations.delegate,
  GlobalCupertinoLocalizations.delegate,
  PhoneFieldLocalization.delegates
],

**Comment by cedvdb** [comment]
Change your code to 

```
localizationsDelegates: const [
   GlobalMaterialLocalizations.delegate,
   GlobalWidgetsLocalizations.delegate,
   GlobalCupertinoLocalizations.delegate,
   ...PhoneFieldLocalization.delegates
],
```

as said in the other issue.

**Comment by Lionapi** [comment]
Thanks a lot. It's working now you can close this issue.
