### ISSUE TITLE
CountryButtonStyle.showDropdownIcon has no effect.

### ISSUE THREAD

**Issue by roman-stakhovskyi** [cedvdb/phone_form_field#239]
Hello. It looks like you forgot to add this field to your _buildCountryButton method.

![Screenshot 2024-04-10 at 15 13 41](https://github.com/cedvdb/phone_form_field/assets/39734933/4a351c96-02da-45a8-bc3a-81f19302d211)

**Comment by cedvdb** [comment]
is fixed on master
