### ISSUE TITLE
[Feature request] Add favorites countries option for country selector

### ISSUE THREAD

**Issue by emri99** [cedvdb/phone_form_field#24]
I would like to define some favorites countries so that my application users can find the mostly used countries in top of the list.
Already started to implements that on my own.

Does this sound like a valuable feature for you ?

**Comment by cedvdb** [comment]
You can already do that with the `countries`  property of the country selector navigator

**Comment by emri99** [comment]
From what I understand, the `countries` property give the available countries. What I mean is to let all the countries available but specify those that are mostly used to be displayed on top of others.

**Comment by emri99** [comment]
> IE: you sort the array of countries given to the navigator. That is why it is here in the first place, it gives more freedom than a `favorite` property. You can sort, remove some countries etc.

I had not thought of this use, although less practical IMHO ;)

**Comment by cedvdb** [comment]
Yes you cannot display a line or any visual delimitation between countries. I actually hesitated between the two implementations when implementing but decided to let the user specify the array directly as it gives more freedom (I had a feature request asking for only a subset of countries).

Two options I see:

 - In the CountrySelector widget have a favorite countries property, that would display the favorites at the top with a delimitation then all countries.
 - a builder ?

**Comment by emri99** [comment]
I have already implemented your first idea (not finished properly). The screenshot is a running example on my current real app. Will push the code ASAP so you can see the code ;)

**Comment by cedvdb** [comment]
Is the delimiter color the default one ? It seems a bit light, if it's not the default could you match it with the search bar ?

**Comment by emri99** [comment]
You can check this branch for the changes : https://github.com/emri99/phone_form_field/tree/add-favorites-countries

> Is the delimiter color the default one ? It seems a bit light, if it's not the default could you match it with the search bar ?

The screenshot is extracted from my real app which uses custom theme values.
I did not change anything explicitly in the code, so it should not be a problem.

> The top padding above the favorites seems to be off as well

I did not change the padding neither.
I have make myself the same remark on the original code. 
My commit doesn't fix this point, this may be changed in another commit.

**Comment by cedvdb** [comment]
Yeah a pull request would be appreciated

**Comment by emri99** [comment]
PR created https://github.com/cedvdb/phone_form_field/pull/26
