### ISSUE TITLE
No event or listner on country code field change

### ISSUE THREAD

**Issue by atakoraworks** [cedvdb/phone_form_field#240]
No event or listner on country code field change. So the issue is that when the user is changing country code from the controller on an app, there is no way to retrieve the fact that a change occurred from the UI. Is this is a bug or on purpose?

We ran into this issue while trying to setup a thing that prompts the user to reverify their phone number after changing it.

**Comment by cedvdb** [comment]
probably a bug, accepting PR

**Comment by cedvdb** [comment]
closing this a this was resolved by the PR above
