### ISSUE TITLE
Example needs to be updated

### ISSUE THREAD

**Issue by rashidotm** [cedvdb/phone_form_field#241]
hi, 

I tried to run the example given in the library but found that I can't run it right away as the package went through some changes that are not reflected in the example.

**Comment by rashidotm** [comment]
btw, same for the example in readme.md.

**Comment by cedvdb** [comment]
Thanks for notifying. If you happen to have a working example on hand a PR would be appreciated. Thanks anyway

**Comment by rashidotm** [comment]
sure, I will. I have never contributed b4 so this will be my first.

**Comment by rashidotm** [comment]
hi,

I am closing this issue as I was using an older package when I reported the issue.
