### ISSUE TITLE
phone number shown in rtl when choosing rtl languages

### ISSUE THREAD

**Issue by rashidotm** [cedvdb/phone_form_field#243]
hi.

I noticed in the demo app that when choosing an rtl language the number format also gets turned to rtl. this makes displaying the number looks erroneous. here is an example: 

![image](https://github.com/cedvdb/phone_form_field/assets/12709757/78f7674c-20e0-4575-82f9-d3918d9b02b5)

the desired behavious is that the number layout remains ltr as this is the natural way of displaying the numbers. or so do I assume.

**Comment by rashidotm** [comment]
just ignore the mentioning of this issue on the pr. it is a mistake.

**Comment by MahMoos** [comment]
This issue still exist in the latest. Could you solve it?

**Comment by cedvdb** [comment]
@MahMoos  someone to land a PR to this library, I'll look at it. It should be pretty straight forward:

https://github.com/cedvdb/phone_numbers_parser

the format method
