### ISSUE TITLE
The dropdown icon will always be displayed if the showDropdownIcon property of the CountryButtonStyle is set to false

### ISSUE THREAD

**Issue by felixmarrero** [cedvdb/phone_form_field#246]
![imagen](https://github.com/cedvdb/phone_form_field/assets/129766523/c1feaeee-f04a-4184-bdb1-e8014c77512e)

The dropdown icon is always show

**Comment by cedvdb** [comment]
This is already fixed on main by this PR https://github.com/cedvdb/phone_form_field/pull/236

**Comment by cedvdb** [comment]
It has now been deployed on pub.dev
