### ISSUE TITLE
FR Support +33 (7) as +33 (6)

### ISSUE THREAD

**Issue by SkilyFrance** [cedvdb/phone_form_field#249]
Hello guys,
First of all thanks for this package.

I'm french developper and have observed a limitation about the french phone format.
With the dial code +33, only phone number starting by "6" are admitted, but now many phone numbers start with "7".

Could you add this option or tell me how do a workaround ?

Thanks for help.

**Comment by cedvdb** [comment]
> but now many phone numbers start with "7"

What does "now" mean ? Since when is this valid ? And what kind of phone number are those (fixedLine or mobile) ? Does it mark the value to be invalid once you input a valid phone number that starts with 7 ?

**Comment by SkilyFrance** [comment]
> > but now many phone numbers start with "7"
> 
> * What does "now" mean ? Was it invalid before and it has recently changed (past few months) or was it valid for a year at least ? Validity of phone numbers change over time and it can take some time for legal changes to reach google repository, then be pulled in this repository. If this is not a new change then:
> * What kind of phone number are those (fixedLine or mobile) ?
> * Does it mark the value to be invalid once you input a valid phone number that starts with 7 or is it just a formatting issue ?

Thanks for your reply.
1. First +33 (7) numbers were born in 10 years ago, now all new numbers start by +33 (7)
2. +33 (6) and +33 (7) are mobile line
3. I use PhoneController's isValid() function to check value. It works on +33(6) but not on +33(7)

Did I answer as you wished ?

**Comment by cedvdb** [comment]
Yes only this is unclear:

 > It works on +33(6) but not on +33(7)
 
 Could you give a full example as both +33(6) and +33(7) are not valid (those are not full phone numbers). I assume you used full phone numbers in reality.
 
 You can see the pattern for validation here: https://github.com/cedvdb/phone_numbers_parser/blob/main/lib/src/metadata/generated/metadata_patterns_by_iso_code.dart#L1184 in the repository https://github.com/cedvdb/phone_numbers_parser

**Comment by SkilyFrance** [comment]
> Yes only this is unclear:
> 
> > It works on +33(6) but not on +33(7)
> 
> Could you give a full example as both +33(6) and +33(7) are not valid (those are not full phone numbers). I assume you used full phone numbers in reality.
> 

Yes for sure : +33 6 00 00 00 00 / +33 7 00 00 00 00  (My phone numbers for test Auth).
Could you provide the fix to put in this pattern or you will update the package ?

**Comment by cedvdb** [comment]
> > Yes only this is unclear:
> > > It works on +33(6) but not on +33(7)
> > 
> > 
> > Could you give a full example as both +33(6) and +33(7) are not valid (those are not full phone numbers). I assume you used full phone numbers in reality.
> 
> Yes for sure : +33 6 00 00 00 00 / +33 7 00 00 00 00 (My phone numbers for test Auth). Could you provide the fix to put in this pattern or you will update the package ?


Are those phone numbers really valid phone numbers ? Those seem strange. A fix should be provided in google https://github.com/google/libphonenumber
