### ISSUE TITLE
How to disable the auto removal of leading zero for specific countries' phone number ?

### ISSUE THREAD

**Issue by dhiaCodes** [cedvdb/phone_form_field#250]
Currently, the package automatically removes the leading zero from phone numbers, which is maybe a standard practice for many countries. In countries like France, the leading zero in phone numbers is significant and should not be removed.
Is there way to disable this ?

**Comment by cedvdb** [comment]
This is done via the package phone_numbers_parser. The 0 in France may be standard practice but I believe it is not significant.

**Comment by cedvdb** [comment]
there is currently no way to do this, feel free to add this in the appropriate package (phone_numbers_parser)
