### ISSUE TITLE
Flutter web html render (--web-renderer html) show flags svgs wrong

### ISSUE THREAD

**Issue by felixmarrero** [cedvdb/phone_form_field#252]
![imagen](https://github.com/user-attachments/assets/dd91e5c5-c2e6-49d4-89f9-2ccc58d8e4b4)

**Comment by cedvdb** [comment]
See: https://github.com/cedvdb/flutter_circle_flags/issues/9

**Comment by felixmarrero** [comment]
can you add a flag like `showFlag` to hide or not the svgs. Actually this prop `showFlag `  is used in the CountryButtonStyle but is not abailable in CountrySelectorNavigator

**Comment by cedvdb** [comment]
It'd be better to fix the issue with the flags than just hide them. I linked an issue above, someone submitted a fix but the fix has been ovewriten by the flag generation. Feel free to add a PR that removes the masks for subsequent flag generation.

Note: Fyi The html renderer will be deprecated

**Comment by cedvdb** [comment]
I will be closing this issue (won't fix) as the html renderer is deprecated.
