### ISSUE TITLE
Localization issue

### ISSUE THREAD

**Issue by erkinovalim** [cedvdb/phone_form_field#256]
the guide in the readme for localization does not work:
`return MaterialApp(
    localizationsDelegates: [
      GlobalMaterialLocalizations.delegate,
      PhoneFieldLocalization.delegate
    ],
    supportedLocales: [
      const Locale('en', ''),
      const Locale('es', ''),
      const Locale('fr', ''),
      const Locale('ru', ''),
      const Locale('uz', ''),
      const Locale('uk', ''),
      // ...
    ],`

instead you need to put this in MaterialApp which works:
`localizationsDelegates: [
          DefaultMaterialLocalizations.delegate,
          ...PhoneFieldLocalization.delegates,
        ],
        supportedLocales: [
      const Locale('en', ''),
      const Locale('es', ''),
      const Locale('fr', ''),
      const Locale('ru', ''),
      const Locale('uz', ''),
      const Locale('uk', ''),
      // ...
    ],`

**Comment by cedvdb** [comment]
Can you submit a PR to update the readme ?

**Comment by erkinovalim** [comment]
Fixed in #257

**Comment by cedvdb** [comment]
Thanks !
