### ISSUE TITLE
onSubmitting is not implemented

### ISSUE THREAD

**Issue by ChreSyr** [cedvdb/phone_form_field#263]
Hello @cedvdb ! Congrats on your package, it is great ! I will integrate it in my own form package, wo_form.

I noticed a small issue, PhoneFormField.onSubmitting is not implemented, you just need to add the following line at line 120 of phone_form_field_state.dart :
```
onSubmitting: widget.onSubmitting,
```

**Comment by cedvdb** [comment]
PRs are welcome

**Comment by cedvdb** [comment]
`onSubmitted` should be usable in v 10.0.0
