### ISSUE TITLE
Circle flags not loading

### ISSUE THREAD

**Issue by vaulient** [cedvdb/phone_form_field#5]
I checked the HEX circle flag repo all the flags are in SVG but some reason my app is loading in png

![Screenshot 2021-08-05 222536](https://user-images.githubusercontent.com/57391221/128366878-58421307-432a-478f-be61-84f668bdd6b1.png)

**Comment by cedvdb** [comment]
I'll check what's up in an hour

**Comment by cedvdb** [comment]
The files are indeed in svg as flutter does not support (at least at the time of doing this lib) svg format without dependencies.

**Comment by cedvdb** [comment]
Do you have any logs ? I just test it right now and those are loading

**Comment by vaulient** [comment]
Well i'll be damned, seems to work now, Just opened up my ide to get the logs you asked for so when I ran the app again, it's working now. Thank you, bro.

Also, one final question,


Is it possible to limit the country selection?? Say if I only want to have only 1 country ?

**Comment by cedvdb** [comment]
it would be easy to add. I have a substantial update coming, awaiting for the flutter 2.3, I'll remember this feature request

**Comment by vaulient** [comment]
Duly noted bro, thank you, really.

Another suggestion would be to allow us to allocate a max value length, that feature would be great too.

**Comment by cedvdb** [comment]
I understand the need if there was no validation but here there is validation (unless you disable it).

**Comment by vaulient** [comment]
I can't seem to find anything on your documentation regarding the validation for max length? My country code (Malaysia) has both 10 digit num and 11 digit num, however the when I use a 11 digit number it shows the invalid phone number message and I'm unable to continue with my form submission

**Comment by cedvdb** [comment]
thanks for the feedback I'll look into that> could you give me an example phone number ?

**Comment by vaulient** [comment]
Sure thing bro, an example would be +60111222244444 (where the number length is calculated from 0)

**Comment by cedvdb** [comment]
Hey @vaulient I had a look today at the issue with the phone number validation. It appears that either google data on phone numbers is wrong or this phone number is incorrect. Do you live in Malaysia and know for sure this is a correct phone number ? It seems like there is 1 too many digit there.
