### ISSUE TITLE
Is it possible to capture/override the keyboard TextInputAction?

### ISSUE THREAD

**Issue by agramian** [cedvdb/phone_form_field#54]
When the soft keyboard [text input action](https://api.flutter.dev/flutter/services/TextInputAction-class.html) is pressed, I would like to capture the event and submit the phone number value or close the keyboard.
Is this currently possible?

On Android it is possible to close the keyboard by pressing the back button however the text input action key does not do anything.
For iOS since my particular test device does not have a back button and the text input action key does not do anything like with Android, the keyboard cannot be closed at all.

**Comment by cedvdb** [comment]
Hello, 

Would onEditingComplete work for your usecase ?

Side note: v4.0.0 has been released with lots of good changes and breaking ones too.

**Comment by cedvdb** [comment]
Is this still an issue ?

**Comment by agramian** [comment]
I have not had a chance to upgrade my app to v4 of your library yet to try out your alternative.

Is `onEditingComplete` already exposed so I can try it or that is your proposed solution?

To clarify, [here](https://stackoverflow.com/questions/50107284/how-do-i-change-text-input-action-button-return-enter-key-on-keyboard-in-flutt) is a stackoverflow question which provides an image and description of what I am trying to control.

**Comment by cedvdb** [comment]
https://github.com/cedvdb/phone_form_field/pull/63 should fix this
