### ISSUE TITLE
Customize country list order

### ISSUE THREAD

**Issue by xvrh** [cedvdb/phone_form_field#7]
Hi,
I would like to re-order slightly the country list to show in priority some preferred countries (ie. detected from the timezone etc..).
Can we expose the country list somehow? (in CountrySelectorNavigator?)

**Comment by cedvdb** [comment]
Not currently but that's a good idea.

**Comment by cedvdb** [comment]
Would it be preferable to expose the country list that the user of the library can use to filter or sort or expose a preferred countries that would be displayed at the top ?

**Comment by xvrh** [comment]
I think the first option is fine.

If it's not enough, it should be easy to create a ListView with a custom UI and override the default one.

**Comment by cedvdb** [comment]
Fixed in upcoming 2.1.0
