### ISSUE TITLE
CountryTranslator class should be exposed

### ISSUE THREAD

**Issue by emri99** [cedvdb/phone_form_field#81]
Hello :)

As the user can define its own country list in country selector, the [CountryTranslator](https://github.com/cedvdb/phone_form_field/blob/dev/lib/src/helpers/country_translator.dart) should be exposed to end user

**Comment by cedvdb** [comment]
I do not see the use case, if the user supplies his own country list, it's still countries that are going to be translated anyway.

**Comment by emri99** [comment]
If user want to use the country selector standalone for country selection in a custom widget (like I do) I think it may be required.

BUT This seems required to me as I have to use the old translation function (which was exposed at the time I wrote the code) in my app, though your answer seems so evident too that I need to investigate a little more about this point required or not. I may have created issue without more thinking about it :)

I'll get in touch once I have look at this in detail.
Thanks ;)

**Comment by cedvdb** [comment]
is this still an issue ?

**Comment by emri99** [comment]
I don't have time to check this deeply for now, you can close this issue if you want, I will reopen if I think this can be useful ;)
