### ISSUE TITLE
Flags not showing if the field is not focused

### ISSUE THREAD

**Issue by Gabrielhn** [cedvdb/phone_form_field#85]
Hi, as implementing this (awesome) plugin in one of our projects, we see that the flag selector only appears if:

- The field is focused.
- or, if not, only when has some content on it.

As our use case, we have the phone field along with others in a "form like" page, but phone field itself it is not the one that receives the first focus when that page it's opened , as result of this on load we have the field without the flag there. Image attached

![PNG image](https://user-images.githubusercontent.com/24768037/154475369-73118c87-e8d9-45a0-9791-d6d7db57c2ba.png)

**Comment by Gabrielhn** [comment]
Just saw that is related w/ a a Flutter issue as mentioned in #84

**Comment by cedvdb** [comment]
Yes, and it's coming up quite often here, but I don't think the flutter issue will move. I originally wanted to let them fix that instead of relying on a workaround, but  this issue is posted every now so maybe it's time to have a work around.

In any case, please upvote that issue

**Comment by cedvdb** [comment]
Please try this branch https://github.com/cedvdb/phone_form_field/tree/fixing_unfocus_icon

**Comment by Gabrielhn** [comment]
> Please try this branch https://github.com/cedvdb/phone_form_field/tree/fixing_unfocus_icon
> 
> This is a rework of the internal so I would like some feedback on the visuals which hopefully haven't changed.


Tested here with the new branch and works fine, both this and #86 are fixed in this.
(recorded test attached)

Thanks a lot @cedvdb keep up the good work! 


https://user-images.githubusercontent.com/24768037/154696087-451783f0-47e0-4561-a9d5-2381042bbc5f.mp4
