### ISSUE TITLE
Editing already formatted field moves the cursor

### ISSUE THREAD

**Issue by Gabrielhn** [cedvdb/phone_form_field#86]
Hi, when the input formatter turns active or inactive (according with the selected country phone size) the cursor is moved the end of the field. Happens that if the user decides to edit a number and the position IS NOT the last one, after that the plugin moves the cursor to the end of the field and it causes bad UX.

Video attached:

https://user-images.githubusercontent.com/24768037/154479346-7b65f2d3-0e16-4770-ae80-8a39bafecad7.mov

**Comment by cedvdb** [comment]
I see that the flag is misaligned on your end too. Could you share the configuration you used ?

**Comment by Gabrielhn** [comment]
Sure, configuration above:

Did you think problem w/ the cursor is related w/ the alignment?

```
PhoneFormField(
    focusNode: _bloc.fn1,
    controller: _bloc.cPhone,
    shouldFormat: true,
    defaultCountry: snapshot.data.isoCode,
    decoration: GlDecorations.decoration.copyWith(
      hintText: 'telefone',
      errorBorder: OutlineInputBorder(
        borderSide: const BorderSide(color: Colors.black, width: 3),
        borderRadius: BorderRadius.circular(10),
      ),
    ),
    validator: PhoneValidator.validMobile(errorText: 'telefone inválido'),
    selectorNavigator: const DraggableModalBottomSheetNavigator(),
    flagSize: 25,
    style: GlStyles.regBlack(s: 20),
    showFlagInInput: true,
    enabled: true,
    autofocus: false,
    autocorrect: false,
    autovalidateMode: AutovalidateMode.onUserInteraction,
    onChanged: (PhoneNumber? value) async {
      widget.setPhone(
        CustomPhoneModel(
          isoCode: _bloc.cPhone.value!.isoCode,
          countryCode: '+${_bloc.cPhone.value!.countryCode}',
          fullPhone: '+${_bloc.cPhone.value!.countryCode}${value!.nsn.replaceAll(RegExp(r'[^0-9]'), '')}',
        ),
      );
    },
  ),
```

**Comment by Gabrielhn** [comment]
> No, I just want to know why the flag is misaligned to kill two birds with one stone.

Cool, any additional info needed, just call

**Comment by cedvdb** [comment]
fixed with https://github.com/cedvdb/phone_form_field/pull/87
