### ISSUE TITLE
Expose the validator

### ISSUE THREAD

**Issue by xvrh** [cedvdb/phone_form_field#9]
Currently, the validator is not exposed and is implemented with `_getDefaultValidator` which hardcode an error string "Invalid phone number".

Can we either allow to specify a custom validator or specify the error string (for translations)?

Thanks :-)

**Comment by cedvdb** [comment]
Yes! That is something I wanted to do at first but decided it was better if the library did it itself. 

I'll go back on my decision for the next version that I'll work on today with all your inputs to allow that.

**Comment by cedvdb** [comment]
fixed in next release
